# Generated by Django 3.2 on 2023-01-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='imgportada',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.categorias'),
        ),
        migrations.AddField(
            model_name='imgportada',
            name='title',
            field=models.CharField(default='test', max_length=250),
        ),
    ]
